### ISSUE TITLE
flutter-actions/setup-flutter@v3 will attempt to install flutter_macos_arm64_3.27.0 on macos-13 (x86_64) runner when requested 3.27.0 flutter version

### ISSUE THREAD

**Issue by TarasMazepa** [flutter-actions/setup-flutter#12]
See details in my run: https://github.com/TarasMazepa/stax/actions/runs/12302169227/job/34334404957

<img width="1454" alt="Screenshot 2024-12-12 at 10 08 54 AM" src="https://github.com/user-attachments/assets/bbcc9e36-7a18-409e-8d0d-227606779024" />

**Comment by socheatsok78** [comment]
Please temporary switch to `uses: flutter-actions/setup-flutter@main`, while i'm working on this issue.

**Comment by socheatsok78** [comment]
Fixed, will schedule for release in `v4`.

**Comment by TarasMazepa** [comment]
Thanks for speedy reaction!
