### ISSUE TITLE
Setup Flutter Script doesn't consider MacOS Architecture

### ISSUE THREAD

**Issue by philiparpin** [flutter-actions/setup-flutter#2]
Environment

OS: macOS Montgomery - 12.2.1
Processor: 2.6 GHz Dual-Core Intel Core i5
Flutter version: 3.0.2
Steps to Reproduce

Clone flutter v3.0.2
Navigate to the hello world sample: cd examples/hello_world
Build for iOS: flutter build ios --release --no-codesign
Notice the error: bin/internal/shared.sh: line 225: bin/cache/dart-sdk/bin/dart: Bad CPU type in executable

The setup flutter script doesn't consider the MacOS Architecture. For Flutter V3.0.0 and V3.0.1 the first entry in the releases manifest is the intel one so the intel version is downloaded. For V3.0.2 the first version listed in the manifest is the M1 one therefore the script downloads that.

**Comment by philiparpin** [comment]
https://github.com/flutter/flutter/issues/106054

**Comment by philiparpin** [comment]
https://github.com/flutter/flutter/issues/106054

**Comment by socheatsok78** [comment]
Hi @philiparpin

Thank you for submitting the issue. I'll take a look into it and see what I can do.

**Comment by socheatsok78** [comment]
Please use `flutter-actions/setup-flutter@v2` instead.

**Comment by socheatsok78** [comment]
If the problem still there, feel free to re-open this issue.

**Comment by amaury901130** [comment]
using  `subosito/flutter-action@v2` solve the problem
