### ISSUE TITLE
Can I setup with local flutter sdk?

### ISSUE THREAD

**Issue by hurelhuyag** [flutter-actions/setup-flutter#4]
The problem is flutter over the internet is too slow. If Is there a way to use locally installed flutter SDK? It will save huge time saver.

**Comment by socheatsok78** [comment]
Are you running on a self-hosted runner?  

On self-hosted that have Flutter SDK installed locally you can use the CLI directly without using this action. Make sure that you add the flutter tool to your path.

**Linux / MacOS**
```
- run: echo "path-to-your-local-flutter/bin" >> $GITHUB_PATH
```

**Windows**
```
- run: echo "path-to-your-local-flutter/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
```

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path
